name: Development Task
description: Internal development task
body:
  - type: textarea
    id: task
    attributes:
      label: Task
  - type: textarea
    id: files
    attributes:
      label: Files
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
